### ISSUE TITLE
Implement flags in command line

### ISSUE THREAD

**Issue by claudiosegala** [claudiosegala/jvm#2]
// lê e exibe o arquivo (tem que perguntar o nome do arquivo de entrada)
./a.out -l

// lê e exibe o arquivo passado
./a.out -l "filename"
./a.out "filename" -l

// roda o arquivo (tem que perguntar o nome do arquivo de entrada)
./a.out 

// roda o arquivo passado
./a.out "filename"

**Comment by lightguy875** [comment]
Done
